
version: 0.0
os: linux
files:
  - source: /
    destination: /app
    overwrite: true 

hooks:
  ApplicationStop:
    - location: scripts/app_stop.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/app_deploy.sh
      timeout: 300
      runas: ec2-user
