
version: 0.0
os: linux
files:
  - source: /
    destination: /app

hooks:
 BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/app_stop.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/app_deploy.sh
      timeout: 300
      runas: root




