
version: 0.0
os: linux
files:
  - source: /
    destination: /app

hooks:
  ApplicationStop:
    - location: scripts/app_stop.sh
      timeout: 300
      runas: root

  BeforeInstall:
    - location: scripts/app_install.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/app_start.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/app_deploy.sh
      timeout: 300
      runas: root
