apiVersion: apps/v1
kind: Deployment
metadata:
  name: movieapp
  labels:
    app: movieapp
spec:
  replicas: 3  # Number of replicas
  selector:
    matchLabels:
      app: movieapp
  template:
    metadata:
      labels:
        app: movieapp
    spec:
      containers:
      - name: movieapp
        image: 474668386920.dkr.ecr.us-east-2.amazonaws.com/movieapp:latest  # Replace with your image URI
        ports:
        - containerPort: 80
