#!/bin/bash

# Install kubectl
curl -LO "https://amazon-eks.s3.us-east-1.amazonaws.com/1.31.0/2023-10-06/bin/linux/amd64/kubectl" # Adjust the version and URL as necessary
chmod +x ./kubectl
sudo mv ./kubectl /usr/local/bin/kubectl
